Update etcd to 1e488f3548f3c952b9896b9279674420657d7f56

diff --git a/github.com/coreos/etcd/test b/github.com/coreos/etcd/test
--- a/github.com/coreos/etcd/test
+++ b/github.com/coreos/etcd/test
@@ -102,13 +102,16 @@ function integration_pass {
 
 function integration_extra {
 	go test -timeout 1m -v ${RACE} -cpu 1,2,4 "$@" "${REPO_PATH}/client/integration"
-	go test -timeout 15m -v ${RACE} -cpu 1,2,4 "$@" "${REPO_PATH}/clientv3/integration"
+	go test -timeout 20m -v ${RACE} -cpu 1,2,4 "$@" "${REPO_PATH}/clientv3/integration"
 	go test -timeout 1m -v -cpu 1,2,4 "$@" "${REPO_PATH}/contrib/raftexample"
 	go test -timeout 5m -v ${RACE} -tags v2v3 "$@" "${REPO_PATH}/store"
 	go test -timeout 1m -v ${RACE} -cpu 1,2,4 -run=Example "$@" "${TEST[@]}"
 }
 
 function functional_pass {
+  	# Clean up any data and logs from previous runs
+  	rm -rf ./agent-*
+
 	for a in 1 2 3; do
 		mkdir -p ./agent-$a
 		./bin/etcd-agent -etcd-path ./bin/etcd -etcd-log-dir "./agent-$a" -port ":${a}9027" -use-root=false &
@@ -138,10 +141,9 @@ function functional_pass {
 	agent_pids=($agent_pids)
 	kill -s TERM "${agent_pids[@]}"
 	for a in "${agent_pids[@]}"; do wait "$a" || true; done
-	rm -rf ./agent-*
 
 	if [[ "${ETCD_TESTER_EXIT_CODE}" -ne "0" ]]; then
-		echo "FAIL with exit code" ${ETCD_TESTER_EXIT_CODE}
+		echo "--- FAIL: exit code" ${ETCD_TESTER_EXIT_CODE}
 		exit ${ETCD_TESTER_EXIT_CODE}
 	fi
 }
@@ -200,6 +202,7 @@ function cov_pass {
 	# expects to start with a non-empty file
 	cp "$COVERDIR"/etcdserver.coverprofile "$COVERDIR"/cover.out
 	for f in "$COVERDIR"/*.coverprofile; do
+		echo "merging test coverage file ${f}"
 		gocovmerge "$f" "$COVERDIR"/cover.out  >"$COVERDIR"/cover.tmp || failed="$failed $f"
 		if [ -s "$COVERDIR"/cover.tmp ]; then
 			mv "$COVERDIR"/cover.tmp "$COVERDIR"/cover.out
@@ -211,7 +214,7 @@ function cov_pass {
 	# held failures to generate the full coverage file, now fail
 	if [ -n "$failed" ]; then
 		for f in $failed; do
-			echo FAIL "$f"
+			echo "--- FAIL:" "$f"
 		done
 		exit 255
 	fi
@@ -243,13 +246,13 @@ function grpcproxy_pass {
 function release_pass {
 	rm -f ./bin/etcd-last-release
 	# to grab latest patch release; bump this up for every minor release
-	UPGRADE_VER=$(git tag -l --sort=-version:refname "v3.2.*" | head -1)
+	UPGRADE_VER=$(git tag -l --sort=-version:refname "v3.3.*" | head -1)
 	if [ -n "$MANUAL_VER" ]; then
 		# in case, we need to test against different version
 		UPGRADE_VER=$MANUAL_VER
 	fi
 	if [[ -z ${UPGRADE_VER} ]]; then
-		UPGRADE_VER="v3.2.0"
+		UPGRADE_VER="v3.3.0"
 		echo "fallback to" ${UPGRADE_VER}
 	fi
 
@@ -262,7 +265,7 @@ function release_pass {
 	set -e
 	case $result in
 		0)	;;
-		*)	echo "FAIL with" ${result}
+		*)	echo "--- FAIL:" ${result}
 			exit $result
 			;;
 	esac
@@ -272,24 +275,23 @@ function release_pass {
 	mv /tmp/etcd ./bin/etcd-last-release
 }
 
-function fmt_pass {
-	toggle_failpoints disable
-
-	echo "Checking gofmt..."
+function gofmt_pass {
 	fmtRes=$(gofmt -l -s -d "${FMT[@]}")
 	if [ -n "${fmtRes}" ]; then
 		echo -e "gofmt checking failed:\n${fmtRes}"
 		exit 255
 	fi
+}
 
-	echo "Checking govet..."
+function govet_pass {
 	vetRes=$(go vet "${TEST[@]}")
 	if [ -n "${vetRes}" ]; then
 		echo -e "govet checking failed:\n${vetRes}"
 		exit 255
 	fi
+}
 
-	echo "Checking 'go tool vet -all -shadow'..."
+function govet_shadow_pass {
 	fmtpkgs=$(for a in "${FMT[@]}"; do dirname "$a"; done | sort | uniq | grep -v "\\.")
 	fmtpkgs=($fmtpkgs)
 	vetRes=$(go tool vet -all -shadow "${fmtpkgs[@]}" 2>&1 | grep -v '/gw/' || true)
@@ -297,27 +299,30 @@ function fmt_pass {
 		echo -e "govet -all -shadow checking failed:\n${vetRes}"
 		exit 255
 	fi
+}
 
+function shellcheck_pass {
 	if which shellcheck >/dev/null; then
-		echo "Checking shellcheck..."
 		shellcheckResult=$(shellcheck -fgcc build test scripts/* 2>&1 || true)
 		if [ -n "${shellcheckResult}" ]; then
 			echo -e "shellcheck checking failed:\n${shellcheckResult}"
 			exit 255
 		fi
 	fi
+}
 
-	echo "Checking documentation style..."
+function markdown_you_pass {
 	# eschew you
 	yous=$(find . -name \*.md -exec grep -E --color "[Yy]ou[r]?[ '.,;]" {} + | grep -v /v2/ || true)
 	if [ ! -z "$yous" ]; then
 		echo -e "found 'you' in documentation:\n${yous}"
 		exit 255
 	fi
+}
 
+function markdown_marker_pass {
 	# TODO: check other markdown files when marker handles headers with '[]'
 	if which marker >/dev/null; then
-		echo "Checking marker to find broken links..."
 		markerResult=$(marker --skip-http --root ./Documentation 2>&1 || true)
 		if [ -n "${markerResult}" ]; then
 			echo -e "marker checking failed:\n${markerResult}"
@@ -326,9 +331,10 @@ function fmt_pass {
 	else
 		echo "Skipping marker..."
 	fi
+}
 
+function goword_pass {
 	if which goword >/dev/null; then
-		echo "Checking goword..."
 		# get all go files to process
 		gofiles=$(find "${FMT[@]}" -iname '*.go' 2>/dev/null)
 		gofiles_all=($gofiles)
@@ -350,9 +356,10 @@ function fmt_pass {
 	else
 		echo "Skipping goword..."
 	fi
+}
 
+function gosimple_pass {
 	if which gosimple >/dev/null; then
-		echo "Checking gosimple..."
 		gosimpleResult=$(gosimple "${STATIC_ANALYSIS_PATHS[@]}" 2>&1 || true)
 		if [ -n "${gosimpleResult}" ]; then
 			echo -e "gosimple checking failed:\n${gosimpleResult}"
@@ -361,9 +368,10 @@ function fmt_pass {
 	else
 		echo "Skipping gosimple..."
 	fi
+}
 
+function unused_pass {
 	if which unused >/dev/null; then
-		echo "Checking unused..."
 		unusedResult=$(unused "${STATIC_ANALYSIS_PATHS[@]}" 2>&1 || true)
 		if [ -n "${unusedResult}" ]; then
 			echo -e "unused checking failed:\n${unusedResult}"
@@ -372,9 +380,10 @@ function fmt_pass {
 	else
 		echo "Skipping unused..."
 	fi
+}
 
+function staticcheck_pass {
 	if which staticcheck >/dev/null; then
-		echo "Checking staticcheck..."
 		staticcheckResult=$(staticcheck "${STATIC_ANALYSIS_PATHS[@]}" 2>&1 || true)
 		if [ -n "${staticcheckResult}" ]; then
 			# TODO: resolve these after go1.8 migration
@@ -391,9 +400,10 @@ function fmt_pass {
 	else
 		echo "Skipping staticcheck..."
 	fi
+}
 
+function ineffassign_pass {
 	if which ineffassign >/dev/null; then
-		echo "Checking ineffassign..."
 		ineffassignResult=$(ineffassign "${STATIC_ANALYSIS_PATHS[@]}" 2>&1 || true)
 		if [ -n "${ineffassignResult}" ]; then
 			echo -e "ineffassign checking failed:\n${ineffassignResult}"
@@ -402,8 +412,21 @@ function fmt_pass {
 	else
 		echo "Skipping ineffassign..."
 	fi
+}
 
-	echo "Checking for license header..."
+function nakedret_pass {
+	if which nakedret >/dev/null; then
+		nakedretResult=$(nakedret "${STATIC_ANALYSIS_PATHS[@]}" 2>&1 || true)
+		if [ -n "${nakedretResult}" ]; then
+			echo -e "nakedret checking failed:\n${nakedretResult}"
+			exit 255
+		fi
+	else
+		echo "Skipping nakedret..."
+	fi
+}
+
+function license_header_pass {
 	licRes=""
 	files=$(find . -type f -iname '*.go' ! -path './cmd/*' ! -path './gopath.proto/*')
 	for file in $files; do
@@ -415,8 +438,9 @@ function fmt_pass {
 		echo -e "license header checking failed:\n${licRes}"
 		exit 255
 	fi
+}
 
-	echo "Checking receiver names..."
+function receiver_name_pass {
 	recvs=$(grep 'func ([^*]' {*,*/*,*/*/*}.go  | grep -Ev "(generated|pb/)" | tr  ':' ' ' |  \
 		awk ' { print $2" "$3" "$4" "$1 }' | sed "s/[a-zA-Z\.]*go//g" |  sort  | uniq  | \
 		grep -Ev  "(Descriptor|Proto|_)"  | awk ' { print $3" "$4 } ' | sort | uniq -c | grep -v ' 1 ' | awk ' { print $2 } ')
@@ -428,8 +452,9 @@ function fmt_pass {
 		done
 		exit 255
 	fi
+}
 
-	echo "Checking commit titles..."
+function commit_title_pass {
 	git log --oneline "$(git merge-base HEAD master)"...HEAD | while read -r l; do
 		commitMsg=$(echo "$l" | cut -f2- -d' ')
 		if [[ "$commitMsg" == Merge* ]]; then
@@ -450,6 +475,31 @@ function fmt_pass {
 			echo "Got: $l"
 			exit 255
 		fi
+	done
+}
+
+function fmt_pass {
+	toggle_failpoints disable
+
+	for p in gofmt \
+			govet \
+			govet_shadow \
+			shellcheck \
+			markdown_you \
+			markdown_marker \
+			goword \
+			gosimple \
+			unused \
+			staticcheck \
+			ineffassign \
+			nakedret \
+			license_header \
+			receiver_name \
+			commit_title \
+			; do
+		echo "Starting '$p' pass at $(date)"
+		"${p}"_pass "$@"
+		echo "Finished '$p' pass at $(date)"
 	done
 }
 
